name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo_mysql, bcmath
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Pint Linter
        run: ./vendor/bin/pint --test

      - name: Run Tests
        run: php artisan test --coverage
